### ISSUE TITLE
fix: Add support for slug generated pages

### ISSUE THREAD

**Issue by LotharieSlayer** [Emiyaaaaa/next-routes-list#1]
The script doesn't seem to handle generated pages route, is there a way to get them ?
<img width="455" alt="image" src="https://github.com/user-attachments/assets/2a305ea8-1ec3-4690-baae-b18db454b6ea">

**Comment by Emiyaaaaa** [comment]
sorry, this is a compile-time tool so there's no way to get runtime [slug].

**Comment by LotharieSlayer** [comment]
Yes I totally see why and it's not too much of a problem, I was able to find another solution that allows me to resolve the mapping of markdown files located in slugs with fs, thanks anyway!
